on:
  push:
    branches:
      - "manifest/*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vincetse/hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: amd64
          - platform: arm32v6
          - platform: arm64v8

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build
        run: |
          docker build --rm \
            --file ${{ matrix.platform }}.Dockerfile \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            .
