on:
  push:
    branches:
      - "manifest/*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vincetse/hello-world

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'

      - name: gofmt
        run: |
          test -z `gofmt -s -l .`

      - name: go vet
        run: |
          go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

      - name: Run tests
        run: |
          GIN_MODE=debug go test

  build:
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            goarch: amd64
            dockerenv:
          - platform: linux/arm/v6
            goarch: arm
            dockerenv: -e QEMU_CPU=arm1176
          - platform: linux/arm/v8
            goarch: arm64
            dockerenv: -e QEMU_CPU=cortex-a53

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'

      - name: Compile the app
        run: |
          export GOOS=linux GOARCH=${{ matrix.goarch }}
          CGO_ENABLED=0 go build -a -o hello_world

      - name: Should binary info
        run: |
          file hello_world
          sha1sum hello_world

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build image
        run: |
          docker build --rm \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            .

      - name: Run image
        run: |
          docker run --rm \
            --tty \
            ${{ matrix.dockerenv }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --version
